### ISSUE TITLE
#docker compose

### ISSUE THREAD

**Issue by jessecaii** [liliancai/HelloDocker#1]
## Deployment

docker-compose down # shut down current running container

docker-compose build

docker-compose up # or docker-compose up service-name docker-compose up mongo -d

```
// docker-compose.yml
version: '1'

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3001:3001'
    links:
      - mongo
    depends_on:
      - mongo
    # networks:
    #   - my_net

  mongo:
    image: mongo
    ports:
      - '27017:27017'
     volumes:
      - /Users/ye.cai/data/db:/data/db
```
